/* 赛博塔罗 · 78张韦特塔罗牌库
   牌面：Rider–Waite–Smith 1909 年原版（Pamela Colman Smith 绘，公有领域）
   牌义：参考韦特塔罗经典释义整理 */
window.TAROT_CARDS = [
/* ===== 大阿卡纳 Major Arcana ===== */
{id:'maj00', n:'愚者', e:'The Fool', a:'major', k:'maj00', w:'RWS_Tarot_00_Fool.jpg', s:'🌈',
 u:'新的开始，无限可能。带着纯真与勇气迈出第一步，前方是自由与冒险。',
 r:'鲁莽或畏缩不前，计划不周，害怕未知而不敢出发。'},
{id:'maj01', n:'魔术师', e:'The Magician', a:'major', k:'maj01', w:'RWS_Tarot_01_Magician.jpg', s:'🎩',
 u:'创造力与行动力全开，资源就在手边，心想事成的开端。',
 r:'才能被埋没，自信不足，或用力过猛、弄巧成拙。'},
{id:'maj02', n:'女祭司', e:'The High Priestess', a:'major', k:'maj02', w:'RWS_Tarot_02_High_Priestess.jpg', s:'🔮',
 u:'直觉敏锐，答案藏在内心深处。静下来，让智慧自然浮现。',
 r:'忽视直觉，被表象迷惑，情绪与秘密被压抑。'},
{id:'maj03', n:'皇后', e:'The Empress', a:'major', k:'maj03', w:'RWS_Tarot_03_Empress.jpg', s:'🌾',
 u:'丰盛与滋养，创造力绽放。好好爱自己，享受生活的美。',
 r:'过度付出，依赖，创造力受阻，忘了照顾自己。'},
{id:'maj04', n:'皇帝', e:'The Emperor', a:'major', k:'maj04', w:'RWS_Tarot_04_Emperor.jpg', s:'🏛',
 u:'秩序与掌控，理性决策，稳定可靠的力量。',
 r:'固执专断，或失去掌控感，缺乏纪律。'},
{id:'maj05', n:'教皇', e:'The Hierophant', a:'major', k:'maj05', w:'RWS_Tarot_05_Hierophant.jpg', s:'🔑',
 u:'传统的智慧，良师指引，遵循已被验证的路。',
 r:'墨守成规，或想打破规则、走自己的路。'},
{id:'maj06', n:'恋人', e:'The Lovers', a:'major', k:'maj06', w:'RWS_Tarot_06_Lovers.jpg', s:'💞',
 u:'心与心的契合，美好的关系；面临重要选择时，听从内心。',
 r:'关系失衡，诱惑，或逃避选择。'},
{id:'maj07', n:'战车', e:'The Chariot', a:'major', k:'maj07', w:'RWS_Tarot_07_Chariot.jpg', s:'🏇',
 u:'意志坚定，掌控方向，勇往直前必达目标。',
 r:'失控，方向不明，内在冲突让人原地打转。'},
{id:'maj08', n:'力量', e:'Strength', a:'major', k:'maj08', w:'RWS_Tarot_08_Strength.jpg', s:'🦁',
 u:'以柔克刚的勇气，耐心与温柔是最强大的力量。',
 r:'自我怀疑，情绪失控，勉强硬撑。'},
{id:'maj09', n:'隐士', e:'The Hermit', a:'major', k:'maj09', w:'RWS_Tarot_09_Hermit.jpg', s:'🏮',
 u:'向内探索，独处的智慧，寻找属于自己的光。',
 r:'自我封闭，逃避人群，或拒绝别人的帮助。'},
{id:'maj10', n:'命运之轮', e:'Wheel of Fortune', a:'major', k:'maj10', w:'RWS_Tarot_10_Wheel_of_Fortune.jpg', s:'☸️',
 u:'转机出现，命运的齿轮开始转动，顺势而为。',
 r:'时运不济，陷入循环，抗拒改变。'},
{id:'maj11', n:'正义', e:'Justice', a:'major', k:'maj11', w:'RWS_Tarot_11_Justice.jpg', s:'⚖️',
 u:'公正与平衡，因果分明，做正确的决定。',
 r:'失衡，不公，逃避该负的责任。'},
{id:'maj12', n:'倒吊人', e:'The Hanged Man', a:'major', k:'maj12', w:'RWS_Tarot_12_Hanged_Man.jpg', s:'🙃',
 u:'换个角度看世界，暂停不是停滞，以退为进。',
 r:'无谓的牺牲，拖延，卡在原地不肯动。'},
{id:'maj13', n:'死神', e:'Death', a:'major', k:'maj13', w:'RWS_Tarot_13_Death.jpg', s:'🦋',
 u:'旧阶段的结束，蜕变与新生。放下，才能腾出手拥抱新的。',
 r:'抗拒改变，难以割舍，停滞不前。'},
{id:'maj14', n:'节制', e:'Temperance', a:'major', k:'maj14', w:'RWS_Tarot_14_Temperance.jpg', s:'🏺',
 u:'平衡与调和，耐心调出刚刚好的比例。',
 r:'失衡，走极端，内耗。'},
{id:'maj15', n:'恶魔', e:'The Devil', a:'major', k:'maj15', w:'RWS_Tarot_15_Devil.jpg', s:'😈',
 u:'欲望与执念，被某段关系或习惯束缚，先看清它。',
 r:'挣脱枷锁，觉醒，放下执念重获自由。'},
{id:'maj16', n:'高塔', e:'The Tower', a:'major', k:'maj16', w:'RWS_Tarot_16_Tower.jpg', s:'⚡',
 u:'突变与崩塌，真相被揭开。破而后立，在废墟上重建更坚固的。',
 r:'侥幸躲过，或延迟的崩塌，害怕改变。'},
{id:'maj17', n:'星星', e:'The Star', a:'major', k:'maj17', w:'RWS_Tarot_17_Star.jpg', s:'⭐',
 u:'希望与疗愈，灵感降临，温柔的指引就在前方。',
 r:'失去信心，迷茫，暂时看不到光。'},
{id:'maj18', n:'月亮', e:'The Moon', a:'major', k:'maj18', w:'RWS_Tarot_18_Moon.jpg', s:'🌙',
 u:'迷雾与幻象，潜意识涌动。别急着下结论，再等等。',
 r:'拨云见月，真相浮现，恐惧消散。'},
{id:'maj19', n:'太阳', e:'The Sun', a:'major', k:'maj19', w:'RWS_Tarot_19_Sun.jpg', s:'☀️',
 u:'成功与快乐，生命力满格，光明磊落的幸福。',
 r:'快乐被暂时遮挡，或过度乐观需要落地。'},
{id:'maj20', n:'审判', e:'Judgement', a:'major', k:'maj20', w:'RWS_Tarot_20_Judgement.jpg', s:'📯',
 u:'觉醒与重生，使命的召唤，与过去和解。',
 r:'自我怀疑，逃避审视，迟迟不愿做决定。'},
{id:'maj21', n:'世界', e:'The World', a:'major', k:'maj21', w:'RWS_Tarot_21_World.jpg', s:'🌍',
 u:'圆满达成，一个周期完美收尾，新篇章开启。',
 r:'差临门一脚，未竟之事，还差一个收尾。'},

/* ===== 权杖 Wands ===== */
{id:'wands01', n:'权杖一', e:'Ace of Wands', a:'wands', k:'wands01', w:'Wands01.jpg', s:'🔥',
 u:'灵感乍现，行动的火苗被点燃，新的机会来了。',
 r:'动力不足，计划延迟，热情来得快去得也快。'},
{id:'wands02', n:'权杖二', e:'Two of Wands', a:'wands', k:'wands02', w:'Wands02.jpg', s:'🔥',
 u:'站在高处规划未来，远见与抉择。',
 r:'犹豫不决，目光受限，计划被打乱。'},
{id:'wands03', n:'权杖三', e:'Three of Wands', a:'wands', k:'wands03', w:'Wands03.jpg', s:'🔥',
 u:'格局打开，向外拓展，等待远方的回报。',
 r:'进展延误，合作不顺，目光放得太近或太远。'},
{id:'wands04', n:'权杖四', e:'Four of Wands', a:'wands', k:'wands04', w:'Wands04.jpg', s:'🔥',
 u:'阶段性的庆祝，安稳的港湾，和谐的里程碑。',
 r:'根基不稳，庆祝延后，小摩擦不断。'},
{id:'wands05', n:'权杖五', e:'Five of Wands', a:'wands', k:'wands05', w:'Wands05.jpg', s:'🔥',
 u:'竞争与碰撞，头脑风暴，乱中有序。',
 r:'无谓的内耗，逃避冲突，恶性竞争。'},
{id:'wands06', n:'权杖六', e:'Six of Wands', a:'wands', k:'wands06', w:'Wands06.jpg', s:'🔥',
 u:'胜利与认可，努力被看见，凯旋而归。',
 r:'缺乏认可，骄傲自满，或暂时的失利。'},
{id:'wands07', n:'权杖七', e:'Seven of Wands', a:'wands', k:'wands07', w:'Wands07.jpg', s:'🔥',
 u:'坚守立场，以一敌众也不退缩。',
 r:'疲于应对，想放弃抵抗，压力超载。'},
{id:'wands08', n:'权杖八', e:'Eight of Wands', a:'wands', k:'wands08', w:'Wands08.jpg', s:'🔥',
 u:'进展神速，好消息在路上，顺风局。',
 r:'停滞，延误，消息迟到。'},
{id:'wands09', n:'权杖九', e:'Nine of Wands', a:'wands', k:'wands09', w:'Wands09.jpg', s:'🔥',
 u:'带伤坚持，最后一段路的倔强与警惕。',
 r:'心力交瘁，戒备过度，真的需要休息了。'},
{id:'wands10', n:'权杖十', e:'Ten of Wands', a:'wands', k:'wands10', w:'Wands10.jpg', s:'🔥',
 u:'扛起重担，责任在肩，咬牙坚持。',
 r:'学会放手，卸下不属于你的负担。'},
{id:'wands11', n:'权杖侍从', e:'Page of Wands', a:'wands', k:'wands11', w:'Wands11.jpg', s:'🔥',
 u:'热情的新人，好奇探索，好消息传来。',
 r:'三分钟热度，方向不明，坏消息。'},
{id:'wands12', n:'权杖骑士', e:'Knight of Wands', a:'wands', k:'wands12', w:'Wands12.jpg', s:'🔥',
 u:'行动派，冲劲十足，说走就走。',
 r:'鲁莽冲动，半途而废，火气太大。'},
{id:'wands13', n:'权杖王后', e:'Queen of Wands', a:'wands', k:'wands13', w:'Wands13.jpg', s:'🔥',
 u:'自信有魅力，温暖的领导力，活出自己。',
 r:'嫉妒，缺乏自信，情绪化。'},
{id:'wands14', n:'权杖国王', e:'King of Wands', a:'wands', k:'wands14', w:'Wands14.jpg', s:'🔥',
 u:'天生的领袖，远见与魄力，掌控全局。',
 r:'专横急躁，独断专行。'},

/* ===== 圣杯 Cups ===== */
{id:'cups01', n:'圣杯一', e:'Ace of Cups', a:'cups', k:'cups01', w:'Cups01.jpg', s:'💧',
 u:'爱意满溢，新的感情萌芽，心被温柔填满。',
 r:'情感封闭，空虚，爱意受阻。'},
{id:'cups02', n:'圣杯二', e:'Two of Cups', a:'cups', k:'cups02', w:'Cups02.jpg', s:'💧',
 u:'双向奔赴，灵魂共鸣，美好的合作或爱情。',
 r:'关系失衡，误解，渐行渐远。'},
{id:'cups03', n:'圣杯三', e:'Three of Cups', a:'cups', k:'cups03', w:'Cups03.jpg', s:'💧',
 u:'欢聚与友谊，举杯庆祝，被朋友们爱着。',
 r:'塑料情谊，社交疲惫，三角关系。'},
{id:'cups04', n:'圣杯四', e:'Four of Cups', a:'cups', k:'cups04', w:'Cups04.jpg', s:'💧',
 u:'倦怠期，对眼前的机会视而不见，情绪内耗。',
 r:'重新振作，走出低潮，接纳新的可能。'},
{id:'cups05', n:'圣杯五', e:'Five of Cups', a:'cups', k:'cups05', w:'Cups05.jpg', s:'💧',
 u:'失落与遗憾，为打翻的杯子难过。',
 r:'走出阴霾，回头看见还拥有的，重拾希望。'},
{id:'cups06', n:'圣杯六', e:'Six of Cups', a:'cups', k:'cups06', w:'Cups06.jpg', s:'💧',
 u:'怀旧与纯真，旧人重逢，被温柔以待。',
 r:'沉溺过去，无法向前，旧课题浮现。'},
{id:'cups07', n:'圣杯七', e:'Seven of Cups', a:'cups', k:'cups07', w:'Cups07.jpg', s:'💧',
 u:'选择太多像雾里看花，小心白日梦。',
 r:'迷雾散去，看清现实，做出选择。'},
{id:'cups08', n:'圣杯八', e:'Eight of Cups', a:'cups', k:'cups08', w:'Cups08.jpg', s:'💧',
 u:'转身离开，去追寻更有意义的东西。',
 r:'徘徊不定，害怕离开，错过时机。'},
{id:'cups09', n:'圣杯九', e:'Nine of Cups', a:'cups', k:'cups09', w:'Cups09.jpg', s:'💧',
 u:'愿望成真，心满意足的幸福感。',
 r:'表面满足，内心空虚，欲望落空。'},
{id:'cups10', n:'圣杯十', e:'Ten of Cups', a:'cups', k:'cups10', w:'Cups10.jpg', s:'💧',
 u:'圆满的爱与家庭，幸福结局的模样。',
 r:'家庭失和，理想破灭，关系疏离。'},
{id:'cups11', n:'圣杯侍从', e:'Page of Cups', a:'cups', k:'cups11', w:'Cups11.jpg', s:'💧',
 u:'浪漫的消息，温柔的心意，灵感与直觉。',
 r:'情绪化，不成熟，幻想破灭。'},
{id:'cups12', n:'圣杯骑士', e:'Knight of Cups', a:'cups', k:'cups12', w:'Cups12.jpg', s:'💧',
 u:'浪漫的追求者，带着邀请而来，跟随内心。',
 r:'虚假承诺，情绪化，逃避现实。'},
{id:'cups13', n:'圣杯王后', e:'Queen of Cups', a:'cups', k:'cups13', w:'Cups13.jpg', s:'💧',
 u:'共情与温柔，直觉敏锐，被爱包围。',
 r:'情绪淹没，过度敏感，情感依赖。'},
{id:'cups14', n:'圣杯国王', e:'King of Cups', a:'cups', k:'cups14', w:'Cups14.jpg', s:'💧',
 u:'情绪成熟，外柔内刚，能稳稳接住爱。',
 r:'情感压抑，操控，冷漠。'},

/* ===== 宝剑 Swords ===== */
{id:'swords01', n:'宝剑一', e:'Ace of Swords', a:'swords', k:'swords01', w:'Swords01.jpg', s:'⚔️',
 u:'思维清晰如剑，真相大白，突破僵局。',
 r:'思绪混乱，误判，沟通不畅。'},
{id:'swords02', n:'宝剑二', e:'Two of Swords', a:'swords', k:'swords02', w:'Swords02.jpg', s:'⚔️',
 u:'僵局与回避，蒙眼不看，内心矛盾。',
 r:'打破僵局，面对真相，做出决定。'},
{id:'swords03', n:'宝剑三', e:'Three of Swords', a:'swords', k:'swords03', w:'Swords03.jpg', s:'⚔️',
 u:'心碎与悲伤，扎心的真相。',
 r:'开始疗愈，走出伤痛，慢慢释怀。'},
{id:'swords04', n:'宝剑四', e:'Four of Swords', a:'swords', k:'swords04', w:'Swords04.jpg', s:'⚔️',
 u:'暂停休息，恢复元气，让大脑关机一会儿。',
 r:'过度休息或无法休息，倦怠，被迫停摆。'},
{id:'swords05', n:'宝剑五', e:'Five of Swords', a:'swords', k:'swords05', w:'Swords05.jpg', s:'⚔️',
 u:'冲突与争执，赢了争吵输了关系。',
 r:'和解，放下争执，修复关系。'},
{id:'swords06', n:'宝剑六', e:'Six of Swords', a:'swords', k:'swords06', w:'Swords06.jpg', s:'⚔️',
 u:'离开困境，驶向平静，过渡期。',
 r:'无法脱身，拖延，旧问题缠身。'},
{id:'swords07', n:'宝剑七', e:'Seven of Swords', a:'swords', k:'swords07', w:'Swords07.jpg', s:'⚔️',
 u:'策略与隐瞒，独自行动，需要留个心眼。',
 r:'谎言揭穿，良心不安，物归原主。'},
{id:'swords08', n:'宝剑八', e:'Eight of Swords', a:'swords', k:'swords08', w:'Swords08.jpg', s:'⚔️',
 u:'自我束缚，觉得走投无路，其实绳结很松。',
 r:'挣脱束缚，找到出路，重获自由。'},
{id:'swords09', n:'宝剑九', e:'Nine of Swords', a:'swords', k:'swords09', w:'Swords09.jpg', s:'⚔️',
 u:'焦虑与噩梦，精神压力拉满。',
 r:'走出焦虑，求助，噩梦醒来。'},
{id:'swords10', n:'宝剑十', e:'Ten of Swords', a:'swords', k:'swords10', w:'Swords10.jpg', s:'⚔️',
 u:'跌到谷底，痛苦的结束，最坏已经发生。',
 r:'触底反弹，复原，熬过来了。'},
{id:'swords11', n:'宝剑侍从', e:'Page of Swords', a:'swords', k:'swords11', w:'Swords11.jpg', s:'⚔️',
 u:'好奇心与警觉，新想法，多观察少说话。',
 r:'多疑，流言，思维混乱。'},
{id:'swords12', n:'宝剑骑士', e:'Knight of Swords', a:'swords', k:'swords12', w:'Swords12.jpg', s:'⚔️',
 u:'果断出击，行动迅速，直言不讳。',
 r:'鲁莽，言语伤人，冲动。'},
{id:'swords13', n:'宝剑王后', e:'Queen of Swords', a:'swords', k:'swords13', w:'Swords13.jpg', s:'⚔️',
 u:'理性独立，洞察力惊人，清醒而自由。',
 r:'冷漠刻薄，过于严苛，心门紧闭。'},
{id:'swords14', n:'宝剑国王', e:'King of Swords', a:'swords', k:'swords14', w:'Swords14.jpg', s:'⚔️',
 u:'智慧与公正，清晰冷静的判断力。',
 r:'滥用权力，冷酷，独断。'},

/* ===== 星币 Pentacles ===== */
{id:'pents01', n:'星币一', e:'Ace of Pentacles', a:'pentacles', k:'pents01', w:'Pents01.jpg', s:'🪙',
 u:'财富的种子，务实的新开始，稳稳的第一步。',
 r:'机会流失，贪心，投资失利。'},
{id:'pents02', n:'星币二', e:'Two of Pentacles', a:'pentacles', k:'pents02', w:'Pents02.jpg', s:'🪙',
 u:'灵活平衡多条线，忙而有序。',
 r:'失衡，手忙脚乱，入不敷出。'},
{id:'pents03', n:'星币三', e:'Three of Pentacles', a:'pentacles', k:'pents03', w:'Pents03.jpg', s:'🪙',
 u:'团队协作，专业被认可，技艺精进。',
 r:'配合不佳，敷衍了事，缺乏认可。'},
{id:'pents04', n:'星币四', e:'Four of Pentacles', a:'pentacles', k:'pents04', w:'Pents04.jpg', s:'🪙',
 u:'储蓄与保守，紧握已有的安全感。',
 r:'过度吝啬或挥霍，学会松手。'},
{id:'pents05', n:'星币五', e:'Five of Pentacles', a:'pentacles', k:'pents05', w:'Pents05.jpg', s:'🪙',
 u:'匮乏与困境，感觉被排除在外。',
 r:'走出困境，获得援助，情况好转。'},
{id:'pents06', n:'星币六', e:'Six of Pentacles', a:'pentacles', k:'pents06', w:'Pents06.jpg', s:'🪙',
 u:'慷慨给予，公平分配，善意的流动。',
 r:'带条件的施舍，债务，不公平。'},
{id:'pents07', n:'星币七', e:'Seven of Pentacles', a:'pentacles', k:'pents07', w:'Pents07.jpg', s:'🪙',
 u:'耐心耕耘，等待收获，评估投入。',
 r:'投入无回报，急于求成，想放弃。'},
{id:'pents08', n:'星币八', e:'Eight of Pentacles', a:'pentacles', k:'pents08', w:'Pents08.jpg', s:'🪙',
 u:'专注打磨技艺，勤勉的匠人精神。',
 r:'敷衍，完美主义卡壳，缺乏动力。'},
{id:'pents09', n:'星币九', e:'Nine of Pentacles', a:'pentacles', k:'pents09', w:'Pents09.jpg', s:'🪙',
 u:'丰足独立，优雅享受努力的成果。',
 r:'过度依赖，财务不稳，享受打折。'},
{id:'pents10', n:'星币十', e:'Ten of Pentacles', a:'pentacles', k:'pents10', w:'Pents10.jpg', s:'🪙',
 u:'长期的稳定与传承，家族般的丰盛。',
 r:'财务纠纷，短视，根基动摇。'},
{id:'pents11', n:'星币侍从', e:'Page of Pentacles', a:'pentacles', k:'pents11', w:'Pents11.jpg', s:'🪙',
 u:'踏实学习新技能，务实的好开端。',
 r:'拖延，眼高手低，浪费。'},
{id:'pents12', n:'星币骑士', e:'Knight of Pentacles', a:'pentacles', k:'pents12', w:'Pents12.jpg', s:'🪙',
 u:'稳健可靠，按部就班，说到做到。',
 r:'停滞死板，过于保守，原地踏步。'},
{id:'pents13', n:'星币王后', e:'Queen of Pentacles', a:'pentacles', k:'pents13', w:'Pents13.jpg', s:'🪙',
 u:'务实丰盛，会照顾人也会过日子。',
 r:'操心过度，忽视自己，物质焦虑。'},
{id:'pents14', n:'星币国王', e:'King of Pentacles', a:'pentacles', k:'pents14', w:'Pents14.jpg', s:'🪙',
 u:'稳健的成功，慷慨的掌舵人。',
 r:'贪婪，固执，物质至上。'}
];
